### ISSUE TITLE
Add https://github.com/LedgerHQ/ledger-u2f-javacard maybe?

### ISSUE THREAD

**Issue by xaduha** [martinpaljak/AppletPlayground#14]
Haven't tried it and not an expert in this area, but it seems legit to me.

**Comment by martinpaljak** [comment]
Sure, Why close ?

**Comment by xaduha** [comment]
It was hanging around for a long time, I closed a bunch of issues I created that had nothing happing in them, just to clean things a bit.

**Comment by martinpaljak** [comment]
I will add and update a bunch of applets that have surfaced lately before FOSDEM 17. It is purely for educational purposes, so ...
