### ISSUE TITLE
openpgpcard has moved to github

### ISSUE THREAD

**Issue by hexum** [martinpaljak/AppletPlayground#16]
More info.
https://sourceforge.net/p/javacardopenpgp/code/14/

Now it's accessible by this URL.
https://github.com/jderuiter/javacard-openpgpcard

**Comment by hexum** [comment]
Now you can refer it as submodule.

**Comment by martinpaljak** [comment]
For the time being I think I will follow the ykneo-openpgp fork (seems more active)
