### ISSUE TITLE
Error "APDU cannot be resolved to a type

### ISSUE THREAD

**Issue by akritidogra** [martinpaljak/AppletPlayground#20]
I am getting this error "APDU cannot be resolved to a type". I think there's some library issue but i'm really not able to solve it. Please help

**Comment by martinpaljak** [comment]
Could you elaborate?

**Comment by akritidogra** [comment]
Im trying to run this code of yours "https://github.com/martinpaljak/AppletPlayground/blob/master/src/be/fedict/eidapplet/EidCard.java"

or any other project of java card. I'm getting the same error. All header files  are underlined red for error

**Comment by martinpaljak** [comment]
Which means you did not export it correctly, with submodules, so that the JC kit would also be present. Are you sure you followed the README?

**Comment by akritidogra** [comment]
okay
