### ISSUE TITLE
Encryption/Decryption using java card

### ISSUE THREAD

**Issue by akritidogra** [martinpaljak/AppletPlayground#22]
I have tried to create a java card applet which performs encryption using AES 128 CBC cipher.I used the Cipher class update() and doFinal() methods for the same. The applet is not encrypting more than 128 bytes.It shows error 6f00 when I send data beyond 128 bytes.Any reason why?

Also I was trying to use Random Data class to generate random data.I was trying to create ALG_SECURE_RANDOM instance but am unable to do so hence I had to use ALG_PSEUDO_RANDOM instance.Can you please help me with the same.

**Comment by martinpaljak** [comment]
You are better off at stackoverflow with such questions - and even there you need to provide source code, input that fails etc.
