### ISSUE TITLE
Securty hole in the OpenPGP applet

### ISSUE THREAD

**Issue by jgoerzen** [martinpaljak/AppletPlayground#7]
Hi folks,

You should probalby apply this patch:

https://github.com/Yubico/ykneo-openpgp/commit/01fdcc1623885d35b959d31759eb25ca49376feb

**Comment by martinpaljak** [comment]
Or maybe leave this as a pracitcal task? The purpose of the AppletPlayground is exactly as advertised: to be educational.

**Comment by hexum** [comment]
We should use upstream code #16

**Comment by hexum** [comment]
Fixed in upstream
https://github.com/jderuiter/javacard-openpgpcard/issues/1

**Comment by martinpaljak** [comment]
Closed by e60e465
